/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.ext4j.taglib.tag.repeater;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import javax.servlet.jsp.JspException;
import javax.servlet.jsp.tagext.Tag;
import net.sourceforge.ext4j.taglib.tag.repeater.FooterTemplateTag;
import net.sourceforge.ext4j.taglib.tag.repeater.RepeaterTag;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestFooterTemplateTag {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      FooterTemplateTag footerTemplateTag0 = new FooterTemplateTag();
      RepeaterTag repeaterTag0 = new RepeaterTag();
      footerTemplateTag0.setParent((Tag) repeaterTag0);
      int int0 = footerTemplateTag0.doStartTag();
      assertEquals(0, int0);
  }

  @Test
  public void test1()  throws Throwable  {
      FooterTemplateTag footerTemplateTag0 = new FooterTemplateTag();
      try {
        footerTemplateTag0.doStartTag();
        fail("Expecting exception: JspException");
      } catch(JspException e) {
        /*
         * Must be used inside a RepeaterTag.
         */
      }
  }
}
