/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.ext4j.taglib.tag;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.util.HashMap;
import java.util.Set;
import javax.servlet.jsp.JspException;
import javax.servlet.jsp.JspTagException;
import net.sourceforge.ext4j.taglib.tag.ForEachTag;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestForEachTag {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ForEachTag forEachTag0 = new ForEachTag();
      forEachTag0.setItems((Object) "ch.qos.logback.core.FileAppender[null]");
      int int0 = forEachTag0.doStartTag();
      assertEquals(1, int0);
  }

  @Test
  public void test1()  throws Throwable  {
      ForEachTag forEachTag0 = new ForEachTag();
      HashMap<Iterable<Object>, Iterable<Integer>> hashMap0 = new HashMap<Iterable<Object>, Iterable<Integer>>();
      Set<Iterable<Object>> set0 = hashMap0.keySet();
      forEachTag0.setItems((Object) set0);
      int int0 = forEachTag0.doStartTag();
      assertEquals(0, int0);
  }
}
