/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.ext4j.taglib.tag;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.util.Iterator;
import net.sourceforge.ext4j.taglib.tag.Breadcrumb;
import net.sourceforge.ext4j.taglib.tag.Breadcrumbs;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestBreadcrumbs {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Breadcrumbs breadcrumbs0 = new Breadcrumbs();
      Iterator<Breadcrumb> iterator0 = breadcrumbs0.iterator();
      assertEquals(false, iterator0.hasNext());
  }

  @Test
  public void test1()  throws Throwable  {
      Breadcrumbs breadcrumbs0 = new Breadcrumbs();
      Breadcrumbs breadcrumbs1 = breadcrumbs0.add("!;2^");
      assertSame(breadcrumbs0, breadcrumbs1);
  }

  @Test
  public void test2()  throws Throwable  {
      Breadcrumbs breadcrumbs0 = new Breadcrumbs();
      Breadcrumbs breadcrumbs1 = breadcrumbs0.add("!;2^", "!;2^");
      assertSame(breadcrumbs1, breadcrumbs0);
  }
}
