/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.ext4j.taglib.tag;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.sourceforge.ext4j.taglib.tag.Breadcrumb;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestBreadcrumb {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Breadcrumb breadcrumb0 = new Breadcrumb("");
      breadcrumb0.setURL("77");
      assertEquals("", breadcrumb0.getName());
  }

  @Test
  public void test1()  throws Throwable  {
      Breadcrumb breadcrumb0 = new Breadcrumb();
      assertNull(breadcrumb0.getURL());
  }

  @Test
  public void test2()  throws Throwable  {
      Breadcrumb breadcrumb0 = new Breadcrumb("Tbs.M ]3z,*", "Tbs.M ]3z,*");
      String string0 = breadcrumb0.getName();
      assertEquals("Tbs.M ]3z,*", string0);
  }

  @Test
  public void test3()  throws Throwable  {
      Breadcrumb breadcrumb0 = new Breadcrumb("");
      String string0 = breadcrumb0.getURL();
      assertNull(string0);
  }

  @Test
  public void test4()  throws Throwable  {
      Breadcrumb breadcrumb0 = new Breadcrumb("");
      breadcrumb0.setName("");
      assertNull(breadcrumb0.getURL());
  }
}
