/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.ext4j.taglib.tag;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.util.Properties;
import net.sourceforge.ext4j.taglib.tag.TagLibConfig;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestTagLibConfig {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Properties properties0 = TagLibConfig.getConfig();
      assertEquals("{}", properties0.toString());
  }

  @Test
  public void test1()  throws Throwable  {
      TagLibConfig tagLibConfig0 = new TagLibConfig();
      Properties properties0 = new Properties();
      tagLibConfig0.setConfig(properties0);
      assertEquals("{}", properties0.toString());
  }

  @Test
  public void test2()  throws Throwable  {
      String string0 = TagLibConfig.getProperty("hrw<1FHJg", "hrw<1FHJg");
      assertEquals("hrw<1FHJg", string0);
  }
}
