/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.ext4j.taglib.tag;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.io.IOException;
import java.util.LinkedList;
import java.util.List;
import javax.servlet.jsp.JspException;
import javax.servlet.jsp.JspWriter;
import javax.servlet.jsp.PageContext;
import net.sourceforge.ext4j.taglib.tag.Breadcrumb;
import net.sourceforge.ext4j.taglib.tag.SimpleBreadcrumbsTag;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestSimpleBreadcrumbsTag {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SimpleBreadcrumbsTag simpleBreadcrumbsTag0 = new SimpleBreadcrumbsTag();
      assertNotNull(simpleBreadcrumbsTag0);
      
      int int0 = simpleBreadcrumbsTag0.doStartTag();
      assertEquals(0, int0);
  }

  @Test
  public void test1()  throws Throwable  {
      SimpleBreadcrumbsTag simpleBreadcrumbsTag0 = new SimpleBreadcrumbsTag();
      assertNotNull(simpleBreadcrumbsTag0);
      
      int int0 = simpleBreadcrumbsTag0.doEndTag();
      assertEquals(6, int0);
  }

  @Test
  public void test2()  throws Throwable  {
      SimpleBreadcrumbsTag simpleBreadcrumbsTag0 = new SimpleBreadcrumbsTag();
      assertNotNull(simpleBreadcrumbsTag0);
      
      simpleBreadcrumbsTag0.setSeparator("Could not instantiate Collection type: ");
      assertEquals("Could not instantiate Collection type: ", simpleBreadcrumbsTag0.getSeparator());
  }

  @Test
  public void test3()  throws Throwable  {
      SimpleBreadcrumbsTag simpleBreadcrumbsTag0 = new SimpleBreadcrumbsTag();
      List<Breadcrumb> list0 = simpleBreadcrumbsTag0.getBreadcrumbs();
      assertNull(list0);
  }

  @Test
  public void test4()  throws Throwable  {
      SimpleBreadcrumbsTag simpleBreadcrumbsTag0 = new SimpleBreadcrumbsTag();
      simpleBreadcrumbsTag0.setPageContext((PageContext) null);
      assertNull(simpleBreadcrumbsTag0.getId());
  }

  @Test
  public void test5()  throws Throwable  {
      SimpleBreadcrumbsTag simpleBreadcrumbsTag0 = new SimpleBreadcrumbsTag();
      String string0 = simpleBreadcrumbsTag0.getSeparator();
      assertNull(string0);
  }

  @Test
  public void test6()  throws Throwable  {
      SimpleBreadcrumbsTag simpleBreadcrumbsTag0 = new SimpleBreadcrumbsTag();
      simpleBreadcrumbsTag0.doInitBody();
      assertEquals(6, simpleBreadcrumbsTag0.doEndTag());
  }

  @Test
  public void test7()  throws Throwable  {
      SimpleBreadcrumbsTag simpleBreadcrumbsTag0 = new SimpleBreadcrumbsTag();
      LinkedList<Breadcrumb> linkedList0 = new LinkedList<Breadcrumb>();
      Breadcrumb breadcrumb0 = new Breadcrumb();
      linkedList0.add(breadcrumb0);
      simpleBreadcrumbsTag0.setBreadcrumbs((List<Breadcrumb>) linkedList0);
      breadcrumb0.setURL("The message for this event has been set already.");
      linkedList0.add(breadcrumb0);
      // Undeclared exception!
      try {
        simpleBreadcrumbsTag0.renderTag((JspWriter) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test8()  throws Throwable  {
      SimpleBreadcrumbsTag simpleBreadcrumbsTag0 = new SimpleBreadcrumbsTag();
      assertNotNull(simpleBreadcrumbsTag0);
      
      int int0 = simpleBreadcrumbsTag0.doAfterBody();
      assertEquals(0, int0);
  }

  @Test
  public void test9()  throws Throwable  {
      SimpleBreadcrumbsTag simpleBreadcrumbsTag0 = new SimpleBreadcrumbsTag();
      simpleBreadcrumbsTag0.renderTag((JspWriter) null);
      assertNull(simpleBreadcrumbsTag0.getId());
  }

  @Test
  public void test10()  throws Throwable  {
      SimpleBreadcrumbsTag simpleBreadcrumbsTag0 = new SimpleBreadcrumbsTag();
      LinkedList<Breadcrumb> linkedList0 = new LinkedList<Breadcrumb>();
      Breadcrumb breadcrumb0 = new Breadcrumb();
      linkedList0.add(breadcrumb0);
      linkedList0.add(breadcrumb0);
      simpleBreadcrumbsTag0.setBreadcrumbs((List<Breadcrumb>) linkedList0);
      // Undeclared exception!
      try {
        simpleBreadcrumbsTag0.renderTag((JspWriter) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
